
langage: c
os: linux
dist: bionic
cache: false

compiler:
  - gcc
  - clang
os: linux

install:
  - sudo apt-get -qq update
  - sudo apt install build-essential zlib1g-dev

before_script:
  - autoreconf -vif


script: 
  - ./configure --enable-wall && make && make check
  - cat test/test-suite.log
