
langage: c
os: linux
dist: bionic
cache: false

compiler:
  - gcc
  - clang
os: linux

arch:
  - amd64
  - arm64

install:
  - sudo apt-get -qq update
  - sudo apt install build-essential zlib1g-dev dos2unix

before_script:
  - autoreconf -vif

script: 
  - ./configure --enable-wall --enable-dwarfexample && make && make check
  - cat test/test-suite.log
